### ISSUE TITLE
Statistics : Change return button / Change size Select button / Progress Bar stats all words

### ISSUE THREAD

**Issue by bastiendearaujo** [WriteInGesturesProject/dev#150]

**Comment by Saxito** [comment]
"Choisi"  with an "S" at the end
Put "Entrainement" in JSON file custom.json
Put memory game with no difficulty

**Comment by Saxito** [comment]
Make marging responsive

**Comment by Saxito** [comment]
Statistique doesn't work with listen and choose Game
