### ISSUE TITLE
Bug Home and Statistiques

### ISSUE THREAD

**Issue by ManonChabre** [WriteInGesturesProject/dev#214]
-  Home : icon about + mettre dev à 0 pour popup de connexion + bienvenue toujours sur le logo (chez moi ?) --> Done

- Statistiques change pas les mots en fonction de mes jeux + remplacer custom par mes mots ? --> Done

**Comment by Saxito** [comment]
bienvenue toujurs sur logo --> done 
Statistique change les mot --> done

**Comment by Saxito** [comment]
Changer la page de chargement avec le logo
